version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_reverse_proxy
    restart: always
    depends_on:
      - fastapi
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
