name: Deployment Pipeline

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy API
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Deploy to Azure VM
              env:
                SERVER_HOST: 4.222.232.53   # Your Azure VM public IP
                SERVER_USER: ezrahel        # Your VM username
                SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}  # SSH key stored in GitHub secrets
              run: |
                printf "%s" "$SERVER_SSH_KEY" > private_key.pem
                chmod 600 private_key.pem
                ls -l private_key.pem

                ssh -o StrictHostKeyChecking=no -i private_key.pem $SERVER_USER@$SERVER_HOST "echo 'SSH connection successful'"

                ssh -o StrictHostKeyChecking=no -i private_key.pem $SERVER_USER@$SERVER_HOST << 'EOF'
                cd ~/fastapi-book-project
                git pull origin main
                docker-compose down
                docker-compose up --build -d
                EOF
