name: Deployment Pipeline

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy API
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set Up Python
              uses: actions/setup-python@v4
              with:
                python-version: python '3.12.6'

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Deploy API
              run: |
                
