name: CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to Azure VM
              uses: appleboy/ssh-action@master
              with:
                  host: 4.222.232.53
                  username: ${{ secrets.SERVER_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd ~/fastapi-book-project
                      docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
                      docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
                      docker compose down
                      docker compose up -d --build
